# External Gems
gems: 						[jekyll-paginate]


# Site Settings
title: 						"Yuguo"
email: 						"me@yuguo.us"
description: 				"《Web全栈工程师的自我修养》作者。"
baseurl: 					""
logourl: 					"/files/common/avatar.jpg"
fa-logo: 					"fa-camera-retro"
paginate: 					5


# Author Settings
author_name: 				"Yuguo"
author_url: 				"http://yuguo.us"
author_bio: 				"《Web全栈工程师的自我修养》作者。"
author_email: 				"me@yuguo.us"
author_image: 				"/files/common/avatar.jpg"


# Social Settings
twitter_url: 				"https://twitter.com/yuguo"
facebook_url: 				"https://www.facebook.com/yuguo"
github_url:  				"https://github.com/yuguo"
# youtube_url:  				"http://youtube.com"
# dribbble_url:  				"http://dribbble.com"
# googleplus_url: 			"http://google.com/plus"
# instagram_url:  			"http://instagram.com"
# pinterest_url:  			"http://pinterest.com"
# linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"yuguo"
theme_google_comments: 		false
theme_analytics_id: 		""
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					weblog/:title/

